### PR TITLE
MonoDevelop scripts

### PR DESCRIPTION
**Pull request by Radivarig**
Scripts and readme for using MonoDevelop

### CODE REVIEW

**Comment by Radivarig** [comment]
Good to go

**Comment by DoctorJellyface** [comment]
Niiice dude. Sorry for responding so late, was away from home all week. I'm gonna test it hopefully on the morrow (though I'm terrible at these kinds of promises), and if all's gonna go well, I'll merge. Thanks for all your work!

**Comment by DoctorJellyface** [comment]
@Radivarig I cannot get this to work. Yes, the script does open MonoDevelop, however, it doesn't open neither the project nor the file. Just a window with the MonoDevelop homepage.

**Comment by Radivarig** [comment]
Hmm.. I'm already using it seamlessly for couple of days. Can you echo the parameters that are sent to monodevelop? put `"${BACKWARD_SLN_DIR}$SLN_NAME $FILE_NAME;$FILE_LINE"` at line 25 [here] (https://github.com/Radivarig/Unity3D-on-Wine/blob/master/text-editors-MonoDevelop/unity3d_native_monodevelop.sh#L25)

**Comment by Radivarig** [comment]
You are missing the required additional `"$(Line)` parameter to send to the external editor, I get the same behavior when I exclude it.

**Comment by DoctorJellyface** [comment]
Nope, the line parameter is definitely set to be sent. Although for some reason Unity thinks that it should pass the same arguments as to the built-in MonoDevelop. I'll try experimenting a bit more.

Also, line number 18 is unneeded. It only produces errors since shell doesn't allow spaces before and after the equals sign.

**Comment by Radivarig** [comment]
I'm on `GNU bash, version 4.3.33` and `Unity 4.6.1f1`
Strangely it works for me with spaces when I run it, so I missed to notice. I pushed the correction.
But I have no idea why would Unity not send the specified args

**Comment by Radivarig** [comment]
Under what name did you save the script?

**Comment by DoctorJellyface** [comment]
I just went Raw -> Save As, so it's under the original.

**Comment by DoctorJellyface** [comment]
`GNU bash 4.3.33(1)` here.

**Comment by Radivarig** [comment]
Try now :)

**Comment by DoctorJellyface** [comment]
OK, great, works now!

I think there are two things to be done before I can merge this:

1. Why do you symlink root to the project folder? Shouldn't you symlink the virtual C: drive, where Unity is installed?
2. We should somehow work around opening JS files, for example in the built-in editor or in a system specified editor.

Otherwise, perfect!

**Comment by Radivarig** [comment]
1) #39 Wine already symlinks `C:` in `~/.local/share/wineprefixes/unity3d/dosdevices` along with other drives where also is `Z:` symlink to root! So inside monodevelop `solution>Assembly-CSharp-vs>References` if you `rightclick>Properties` on `UnityEditor` (or any other with error mark)  all win paths to references start with `Z:` because Unity saves those references in `Assembly-CSharp-vs.csproj` like this:
```
<Reference Include="UnityEngine">
    <HintPath>Z:/home/radivarig/.local/share/wineprefixes/unity3d/drive_c/Program Files/Unity/Editor/Data/Managed/UnityEngine.dll</HintPath>
</Reference>
```
You can ignore the invalid path mark as it is symlinked correctly. My guess is that monodevelop thinks there's error because of space in "Program Files" but path is in win layer environment so it isn't invalid.

2) #42 is still opened, but I'll adapt and push the suggested workaround from there. (I'll need you to test because my Unity sends correct arguments so I had to insert the script to MonoDevelop.exe to get the built-in args :) and for this to work I have to have original MonoDevelop.exe there)

3) If you `man monodevelop` you'll see that native MD has no option `--nologo` but we can ofc send it to built-in.

**Comment by Radivarig** [comment]
Ideally we should use only:
1. native => #42
2. built-in =>  #37, outdated, --nologo is ignored
3. custom editor => no proper auto-completion

#37 is a big deal for me as I use AltGr for `{}[]<>` (tho this is wine problem)

**Comment by Radivarig** [comment]
Note, opening .js in built-in depends on wineprefix, mine is called `unity3d`.
Also, if you replaced MonoDevelop.exe with some script revert it to original.

**Comment by Radivarig** [comment]
One last thing before merge, I have to update both scripts for when unity sends only .sln file (on rightclick>sync md project) or when opening when there is no .sln file like on new project. (~tomorrow)

**Comment by Radivarig** [comment]
Yo, did you test this?

**Comment by DoctorJellyface** [comment]
Nope, hopefully I'll get to it tomorrow.

**Comment by DoctorJellyface** [comment]
Tried it (in Unity 5), and bad news.

I had to delete all the *sln files to get it working and, it opens a new window every time I open a new file. "Sync MonoDevelop project" opens MonoDevelop, but without the project.

**Comment by Radivarig** [comment]
Ok, I know what's happening. I'll fix it soon-ish.

**Comment by Radivarig** [comment]
Fixed

**Comment by DoctorJellyface** [comment]
Seems good! If you don't experience any more problems I think we can merge. Also, do think the Editor attaching option does anything?

**Comment by Radivarig** [comment]
No problems here. For attaching I can't find any technical info on how it's allowed, based on parameters there is no difference in how Unity communicates with builtin and external editor so my guess is it happens in project files.

**Comment by DoctorJellyface** [comment]
OK, merging. I'll update the wiki too.

**Comment by DoctorJellyface** [comment]
Thanks for the great work.

**Comment by Radivarig** [comment]
Glad I could contribute :)

**Pull request merged**
