### PR TITLE
Adjusted for different distros

### PR DESCRIPTION
**Pull request by Radivarig**
Thanks to @dementedhedgehog for reporting the issue and testing on Ubuntu

### CODE REVIEW

**Comment by Radivarig** [comment]
There is also an additional Emacs script

**Comment by DoctorJellyface** [comment]
Why is it changed to bash?

**Comment by dementedhedgehog** [comment]
Most Unixes use(d) bash as an alias for sh anyway.   Ubuntu uses dash as 
an alias for sh.  https://wiki.ubuntu.com/DashAsBinSh  Which means that 
a lot of bash specific syntax in these scripts doesn't work on 
ubuntu-based linuxes.

Rather than change all the scripts to standard sh, specifying the use of 
bash was simpler since that is the language the scripts were actually 
written in.

cheers
     blaize (aka demented hedgehog)

**Comment by DoctorJellyface** [comment]
OK, so ready for merge? (btw @Radivarig do you have merge rights?)

**Comment by Radivarig** [comment]
@DoctorJellyface , seems like I don't even tho I'm added to maintainers group

**Comment by DoctorJellyface** [comment]
Weird. Do you want them, or shall I just merge it?

**Comment by Radivarig** [comment]
Yeah, so I can do merges if there will be any

**Comment by Radivarig** [comment]
By the way, how's the arch package going?

**Comment by DoctorJellyface** [comment]
Done.

You mean the native Unity package? Just check out `unity-editor`, it's been fully functional from day 0.

**Comment by Radivarig** [comment]
Lol, I was searching for unity3d. Cool

**Comment by Radivarig** [comment]
@DoctorJellyface I installed unity-editor but opening in MD is not working, does it open for you (without scripts)?

**Comment by DoctorJellyface** [comment]
Eh? What scripts? Just run `monodevelop-unity`, it's bundled with it.

**Comment by DoctorJellyface** [comment]
And yes, it opens correctly.

**Comment by Radivarig** [comment]
Did a fresh install of unity and opening a script lauched empty MD, so I used my native script, just removed wine path.

**Comment by DoctorJellyface** [comment]
Oh yeah, the Unity-MD don't communicate well, try to first synchronize with MD, and if that doesn't work, simply use the Arch MD.

**Pull request merged**
