### PR TITLE
added wineprefix path from .sln path

### PR DESCRIPTION
**Pull request by Radivarig**
Gets wineprefix folder path from .sln path. Tested both

### CODE REVIEW

**Comment by DoctorJellyface** [comment]
I take your word for it. Thanks!

**Comment by DoctorJellyface** [comment]
@Radivarig also if you want to become a maintainer, just ask!

**Comment by Radivarig** [comment]
Sure :)

**Comment by DoctorJellyface** [comment]
Welcome to the team ;)

**Comment by UncleJey** [comment]
Hi guys! tahoma font is not loading on my ubuntu 15.04 in both wines (1.6 & 1.7)

**Comment by DoctorJellyface** [comment]
Hiya! Please try searching in issues instead of commenting on pul requests though. I think #63 is the issue you are looking for.

**Comment by UncleJey** [comment]
yep. its working. thanx.

**Comment by UncleJey** [comment]
Just leave it there
http://blogs.unity3d.com/2015/08/26/unity-comes-to-linux-experimental-build-now-available/

**Pull request merged**
