### PR TITLE
Updated and cleaned PlayOnLinux script, updated header, standardized.

### PR DESCRIPTION
**Pull request by DoctorJellyface**
_Please_ test this. I haven't, and I don't have the resources to right now. Thanks.

### CODE REVIEW

**Comment by RaphaBarros** [comment]
I'm getting a bunch of crashes throughout the installation process. The last crash gives a 
"Error in POL_Shortcut
Binary not found: Unity.exe
Have you installed the program to the default location?"

**Comment by DoctorJellyface** [comment]
@RaphaBarros I got an email that you replied, but I can't see your comment here. Did you delete it?

**Comment by RaphaBarros** [comment]
Yes. I had a problem but realized it was because wine had been uninstalled in my machine (some problem with cuda/nvidia drivers and wine dependencies). After I resolve this issue I'll try the script again ^^

**Comment by DoctorJellyface** [comment]
Okaay, merged, no idea why github didn't notice this. Note to self, use branches next time.

**Pull request closed without merging**
